# Generated by Django 2.0.4 on 2018-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferee_name', models.CharField(max_length=50)),
                ('transferee_address', models.CharField(max_length=100)),
                ('transferee_nationality', models.CharField(max_length=30)),
                ('transferor_name', models.CharField(max_length=50)),
                ('transferor_address', models.CharField(max_length=100)),
                ('transferor_nationality', models.CharField(max_length=30)),
                ('manufacturer_and_model', models.CharField(max_length=100)),
                ('manufactured', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('serial_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('transfered', models.DateField()),
            ],
        ),
    ]
