# Generated by Django 2.0.4 on 2018-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofsale',
            name='transferor_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='transferor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billofsale',
            name='transferor_nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
