# Generated by Django 2.0.4 on 2018-04-22 17:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0002_auto_20180422_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('manufacturer_and_model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50)),
                ('applicant_name', models.CharField(max_length=50)),
                ('applicant_telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('applicant_address', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_type', models.CharField(choices=[('1', 'Individual'), ('2', 'Partnership'), ('3', 'Corporation'), ('4', 'Co-Owner'), ('5', 'Government'), ('8', 'Non-Citizen Corporation'), ('9', 'Non-Citizen Corporation Co-Owner')], max_length=1)),
                ('registered', models.DateField()),
            ],
        ),
    ]
