# Generated by Django 2.0.4 on 2018-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0003_applicationforregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforregistration',
            name='applicant_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
