# Generated by Django 2.0.4 on 2018-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0004_auto_20180422_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGuarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=50)),
                ('debtor_address', models.CharField(max_length=100)),
                ('assignor_name', models.CharField(max_length=50)),
                ('assignee_name', models.CharField(max_length=50)),
                ('assignor_address', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
