# Generated by Django 2.0.4 on 2018-04-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0005_securityguarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofsale',
            name='tx_hash',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
