# Generated by Django 2.0.4 on 2018-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0006_billofsale_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforregistration',
            name='tx_hash',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityguarantee',
            name='tx_hash',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
