# Generated by Django 2.0.4 on 2018-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0007_auto_20180423_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('original_name', models.CharField(max_length=255)),
                ('uuid_name', models.CharField(max_length=48, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
