# Generated by Django 2.0.4 on 2018-09-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
    ]
