# Generated by Django 2.0.4 on 2018-09-04 10:11

from django.db import migrations, models
import ubitquity.ubitquity.models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0009_auto_20180904_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforregistration',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='billofsale',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='securityguarantee',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=ubitquity.ubitquity.models.get_upload_to),
        ),
    ]
