# Generated by Django 2.0.4 on 2018-09-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubitquity', '0010_auto_20180904_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOnChainBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOnChainGuarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOnChainRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=70)),
            ],
        ),
    ]
